# Generated by Django 2.2.16 on 2021-11-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211130_2016'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_author_text',
        ),
    ]
